### ISSUE TITLE
Cannot find coq-art on opam Coq repo

### ISSUE THREAD

**Issue by ghost** [coq-community/coq-art#7]
Wanted to install coq-art from opam as advised in README.md
> opam repo add coq-released https://coq.inria.fr/opam/released
> [...]
> opam install coq-coq-art
> [ERROR] No package named coq-coq-art found.

opam does not seem to be available
> opam search "coq*art"
> [no coq art here :,( ]

I cannot see it either in http://coq.io/opam/

**Comment by palmskog** [comment]
The inaccurate part of the README.md was autogenerated from our templates, and is fixed by #8.

The recommended use of this repository is to clone it or fork it and build it locally. This allows working on the exercises, which is the main point. It actually doesn't make much sense to publish releases on OPAM, and Coq's OPAM index has rules against developments that contain many `Admitted` lemmas, which this repository has.

**Comment by ghost** [comment]
OK thanks. BTW `make all.pdf` fails on my machine but it may not be that useful either.
